spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dawn
    username: root
    password: KYPiD7rnjzmmmDLs
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
    publisher-returns: true
    publisher-confirm-type: correlated
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li09raH4jFrLkpMY
            client-secret: a360b56c87bffbbb36454f41d14948f442532e76
server:
  port: 8282

ip:
  xdbPath: /data/csdn-ip2region.xdb
upload:
  path: /path/file/
file:
  url: http://120.27.215.0
  path: /files